type DemoOptions = {
  caseId?: string;
  title?: string;
  videos: File[];
};

const cameraNames = [
  "CAM-01",
  "CAM-02",
  "CAM-03",
  "CAM-04",
  "CAM-05",
  "CAM-06",
];

export function buildDemoCase({ caseId, title, videos }: DemoOptions) {
  const mediaUrls = videos.map((file) => URL.createObjectURL(file));
  const video = (index: number) => videos[index] ?? videos.at(-1);
  const clip = (
    index: number,
    summary: string,
    transcript = "",
    visibleText = "",
  ) => ({
    evidence_clip_id: `EV-${cameraNames[index]}-${String(index + 1).padStart(2, "0")}`,
    item_id: `TL-ITEM-${index + 1}`,
    asset_id: `TL-ASSET-${index + 1}`,
    camera_id: cameraNames[index],
    source_filename: video(index)?.name ?? `CAM-${index + 1}.mp4`,
    start_sec: 0,
    end_sec: 9.8,
    summary,
    transcript,
    visible_text: visibleText,
    confidence: 0.9 + index * 0.01,
    source_url: mediaUrls[index] ?? mediaUrls.at(-1) ?? null,
  });

  const clips = [
    clip(
      0,
      "Pre-task briefing establishes the approved controls",
      "P1 goes to Storage Zone B. Keep Walkway A clear. No reversing without clearance.",
      "JHA-MATERIAL-LIFT-07 · SPOTTER REQUIRED",
    ),
    clip(
      1,
      "Assigned spotter leaves while pallet movement continues",
      "B, report to the south gate. Hold position.",
    ),
    clip(
      2,
      "Pallet P1 blocks Walkway A and Worker C detours",
      "The walkway is blocked.",
      "P1 · PEDESTRIAN WALKWAY · LIFT ZONE C",
    ),
    clip(
      3,
      "Forklift T1 reverses without confirmed radio clearance",
      "Spotter B, is the rear clear? ... I’ll back up slowly.",
      "T1 · RADIO CLEARANCE REQUIRED",
    ),
    clip(
      4,
      "Worker C and reversing T1 converge before an emergency stop",
      "STOP!",
      "LIFT ZONE C · EQUIPMENT ONLY",
    ),
    clip(
      5,
      "Supervisor preserves the scene and begins the investigation",
      "Nobody move anything.",
    ),
  ];

  const evidence = (index: number) => [clips[index].evidence_clip_id];
  const record = {
    case_id: caseId || "ST-DEMO-LIFT-C",
    title: title || "Lift Zone C Near-Miss Investigation",
    status: "AWAITING_APPROVAL",
    created_at: "2026-07-30T17:14:50Z",
    updated_at: "2026-07-30T17:16:10Z",
    error: null,
    investigation: {
      case_id: caseId || "ST-DEMO-LIFT-C",
      title: "Blocked Walkway → Forklift Near-Miss",
      incident_summary:
        "SiteTrace reconstructed how a blocked pedestrian route, an absent spotter, and an unconfirmed reverse movement converged into a near miss. No physical contact occurred.",
      incident_overview: [
        {
          claim_id: "CLAIM-01",
          text: "Pallet P1 was placed outside Storage Zone B and obstructed Walkway A.",
          evidence_clip_ids: evidence(2),
          finding_ids: ["DEV-01"],
        },
        {
          claim_id: "CLAIM-02",
          text: "Worker C entered Lift Zone C while Forklift T1 was reversing without captured spotter clearance.",
          evidence_clip_ids: [...evidence(3), ...evidence(4)],
          finding_ids: ["DEV-02", "DEV-03"],
        },
      ],
      event_timeline: [
        {
          claim_id: "TIME-01",
          text: "10:14:50 — The briefing assigns Spotter B and requires a clear walkway and radio clearance.",
          evidence_clip_ids: evidence(0),
          finding_ids: [],
        },
        {
          claim_id: "TIME-02",
          text: "10:15:14 — Spotter B leaves; pallet movement resumes.",
          evidence_clip_ids: evidence(1),
          finding_ids: ["DEV-02"],
        },
        {
          claim_id: "TIME-03",
          text: "10:15:20 — P1 blocks Walkway A; Worker C detours into Lift Zone C.",
          evidence_clip_ids: evidence(2),
          finding_ids: ["DEV-01"],
        },
        {
          claim_id: "TIME-04",
          text: "10:15:35 — T1 reverses without recorded clearance; Supervisor E orders an emergency stop.",
          evidence_clip_ids: [...evidence(3), ...evidence(4)],
          finding_ids: ["DEV-03"],
        },
      ],
      deviation_summary: [
        {
          claim_id: "DEV-SUMMARY-01",
          text: "Four evidence-linked variances were identified; final closeout inspection remains unverified.",
          evidence_clip_ids: [...evidence(1), ...evidence(2), ...evidence(3)],
          finding_ids: ["DEV-01", "DEV-02", "DEV-03", "DEV-04"],
        },
      ],
      planned_steps: [
        {
          step_id: "JHA-01",
          sequence: 1,
          name: "Stage Pallet P1",
          description: "Move P1 into the approved material staging area.",
          required_controls: ["Place material fully inside Storage Zone B"],
          must_avoid_zones: ["Walkway A"],
          required_roles: ["Worker A"],
        },
        {
          step_id: "JHA-02",
          sequence: 2,
          name: "Maintain pedestrian access",
          description: "Keep the designated walkway unobstructed.",
          required_controls: ["Walkway A remains clear"],
          must_avoid_zones: ["Pedestrian route"],
          required_roles: ["Worker A"],
        },
        {
          step_id: "JHA-03",
          sequence: 3,
          name: "Control equipment movement",
          description: "Keep the assigned spotter in position.",
          required_controls: ["Spotter remains until movement is complete"],
          must_avoid_zones: [],
          required_roles: ["Spotter B", "Operator D"],
        },
        {
          step_id: "JHA-04",
          sequence: 4,
          name: "Authorize reversing",
          description: "Require explicit radio confirmation before movement.",
          required_controls: ["Confirmed radio clearance before reversing"],
          must_avoid_zones: ["Blind Spot Zone"],
          required_roles: ["Spotter B", "Operator D"],
        },
        {
          step_id: "JHA-05",
          sequence: 5,
          name: "Close out the task",
          description: "Inspect the walkway and equipment zone.",
          required_controls: ["Final egress inspection"],
          must_avoid_zones: [],
          required_roles: ["Supervisor E"],
        },
      ],
      events: [
        {
          event_id: "EVENT-BRIEFING",
          event_type: "JHA_BRIEFING",
          summary: "Supervisor E communicates the approved controls.",
          camera_id: "CAM-01",
          start_sec: 0,
          end_sec: 9,
          actor_ids: ["SUPERVISOR-E", "WORKER-A", "SPOTTER-B", "OPERATOR-D"],
          object_ids: ["PALLET-P1", "FORKLIFT-T1"],
          zone_ids: ["STORAGE-ZONE-B", "WALKWAY-A"],
          evidence_clip_ids: evidence(0),
          confidence: 0.97,
          observation_type: "observed",
        },
        {
          event_id: "EVENT-SPOTTER-DEPARTURE",
          event_type: "SPOTTER_DEPARTURE",
          summary: "Spotter B leaves while the material movement remains active.",
          camera_id: "CAM-02",
          start_sec: 14,
          end_sec: 17,
          actor_ids: ["SPOTTER-B", "WORKER-A"],
          object_ids: ["PALLET-P1", "RADIO-R1"],
          zone_ids: ["LOADING-AREA"],
          evidence_clip_ids: evidence(1),
          confidence: 0.94,
          observation_type: "observed",
        },
        {
          event_id: "EVENT-WALKWAY-BLOCKED",
          event_type: "STATE_CHANGE",
          summary: "Pallet P1 changes Walkway A from clear to blocked.",
          camera_id: "CAM-03",
          start_sec: 23,
          end_sec: 25,
          actor_ids: ["WORKER-A"],
          object_ids: ["PALLET-P1"],
          zone_ids: ["WALKWAY-A", "STORAGE-ZONE-B"],
          evidence_clip_ids: evidence(2),
          confidence: 0.96,
          observation_type: "observed",
        },
        {
          event_id: "EVENT-DETOUR",
          event_type: "PEDESTRIAN_DETOUR",
          summary: "Worker C leaves Walkway A and enters Lift Zone C.",
          camera_id: "CAM-03",
          start_sec: 27,
          end_sec: 29,
          actor_ids: ["WORKER-C"],
          object_ids: ["PALLET-P1"],
          zone_ids: ["WALKWAY-A", "LIFT-ZONE-C"],
          evidence_clip_ids: evidence(2),
          confidence: 0.92,
          observation_type: "observed",
        },
        {
          event_id: "EVENT-REVERSE",
          event_type: "REVERSE_MOVEMENT",
          summary: "Operator D starts reversing T1 without captured clearance.",
          camera_id: "CAM-04",
          start_sec: 37,
          end_sec: 39,
          actor_ids: ["OPERATOR-D"],
          object_ids: ["FORKLIFT-T1", "RADIO-R1"],
          zone_ids: ["LIFT-ZONE-C"],
          evidence_clip_ids: evidence(3),
          confidence: 0.95,
          observation_type: "observed",
        },
        {
          event_id: "EVENT-NEAR-MISS",
          event_type: "NEAR_MISS",
          summary: "Worker C enters T1’s reverse path; no contact occurs.",
          camera_id: "CAM-05",
          start_sec: 44,
          end_sec: 47,
          actor_ids: ["WORKER-C", "OPERATOR-D"],
          object_ids: ["FORKLIFT-T1"],
          zone_ids: ["LIFT-ZONE-C", "BLIND-SPOT-ZONE"],
          evidence_clip_ids: evidence(4),
          confidence: 0.93,
          observation_type: "observed",
        },
        {
          event_id: "EVENT-STOP",
          event_type: "EMERGENCY_STOP",
          summary: "Supervisor E issues a stop warning and T1 stops.",
          camera_id: "CAM-05",
          start_sec: 47,
          end_sec: 49,
          actor_ids: ["SUPERVISOR-E", "WORKER-C"],
          object_ids: ["FORKLIFT-T1"],
          zone_ids: ["LIFT-ZONE-C"],
          evidence_clip_ids: evidence(4),
          confidence: 0.98,
          observation_type: "observed",
        },
        {
          event_id: "EVENT-PRESERVE",
          event_type: "SCENE_PRESERVATION",
          summary: "The supervisor secures and photographs the incident scene.",
          camera_id: "CAM-06",
          start_sec: 52,
          end_sec: 59,
          actor_ids: ["SUPERVISOR-E", "SPOTTER-B", "WORKER-A", "WORKER-C"],
          object_ids: ["PALLET-P1", "FORKLIFT-T1"],
          zone_ids: ["WALKWAY-A", "LIFT-ZONE-C"],
          evidence_clip_ids: evidence(5),
          confidence: 0.94,
          observation_type: "observed",
        },
      ],
      evidence_clips: clips,
      findings: [
        {
          finding_id: "DEV-01",
          jha_step_id: "JHA-01",
          status: "CONFIRMED_DEVIATION",
          title: "Pallet staged outside the approved zone",
          planned_control: "Place P1 fully inside Storage Zone B.",
          observed_work: "P1 was placed across Walkway A outside Storage Zone B.",
          evidence_clip_ids: evidence(2),
          graph_path_node_ids: [
            "JHA-01",
            "STORAGE-ZONE-B",
            "PALLET-P1",
            "WALKWAY-A",
            "EVENT-DETOUR",
          ],
          graph_path_relationships: [
            "DESTINATION",
            "OUTSIDE_OF",
            "BLOCKS",
            "PRECEDES",
          ],
          confidence: 0.96,
          evidence_gap_reason: null,
          requires_human_review: true,
        },
        {
          finding_id: "DEV-02",
          jha_step_id: "JHA-03",
          status: "CONFIRMED_DEVIATION",
          title: "Assigned spotter left during active work",
          planned_control: "Spotter B remains until movement is complete.",
          observed_work: "Spotter B left and pallet movement resumed.",
          evidence_clip_ids: evidence(1),
          graph_path_node_ids: [
            "JHA-03",
            "SPOTTER-B",
            "EVENT-SPOTTER-DEPARTURE",
            "PALLET-P1",
          ],
          graph_path_relationships: ["REQUIRES", "LEAVES_DURING", "INVOLVES"],
          confidence: 0.94,
          evidence_gap_reason: null,
          requires_human_review: true,
        },
        {
          finding_id: "DEV-03",
          jha_step_id: "JHA-04",
          status: "CONFIRMED_DEVIATION",
          title: "Reverse movement began without confirmed clearance",
          planned_control: "Receive explicit radio clearance before reversing.",
          observed_work: "A clearance request received no audible response before T1 moved.",
          evidence_clip_ids: evidence(3),
          graph_path_node_ids: [
            "JHA-04",
            "RADIO-CLEARANCE",
            "NO-RESPONSE",
            "EVENT-REVERSE",
            "FORKLIFT-T1",
            "EVENT-NEAR-MISS",
          ],
          graph_path_relationships: [
            "REQUIRES",
            "HAS_RESULT",
            "PRECEDES",
            "USES",
            "PRECEDES",
          ],
          confidence: 0.95,
          evidence_gap_reason: null,
          requires_human_review: true,
        },
        {
          finding_id: "DEV-04",
          jha_step_id: "JHA-05",
          status: "UNVERIFIABLE",
          title: "Final closeout inspection cannot be established",
          planned_control: "Inspect Walkway A and Lift Zone C after placement.",
          observed_work: null,
          evidence_clip_ids: [],
          graph_path_node_ids: ["JHA-05", "FINAL-INSPECTION", "EVIDENCE-GAP"],
          graph_path_relationships: ["REQUIRES", "NOT_ESTABLISHED_BY"],
          confidence: 0.72,
          evidence_gap_reason:
            "The uploaded camera windows do not cover the planned closeout interval.",
          requires_human_review: true,
        },
      ],
      corrective_actions: [
        {
          action_id: "ACTION-01",
          finding_id: "DEV-01",
          action_type: "immediate",
          description: "Stop Lift Zone C work, remove P1, and verify Walkway A is clear.",
          owner_role: "Site Supervisor",
          due_date: "Immediate",
          status: "DRAFT",
        },
        {
          action_id: "ACTION-02",
          finding_id: "DEV-02",
          action_type: "corrective",
          description: "Require the named spotter to remain until equipment movement ends.",
          owner_role: "Lift Director",
          due_date: "Before next lift",
          status: "DRAFT",
        },
        {
          action_id: "ACTION-03",
          finding_id: "DEV-03",
          action_type: "preventive",
          description: "Add positive radio-clearance confirmation to the operator checklist.",
          owner_role: "Safety Manager",
          due_date: "2026-07-31",
          status: "DRAFT",
        },
      ],
      limitations: [
        "This is a labeled demo reconstruction generated from the six staged CCTV clips.",
        "The event sequence does not by itself establish organizational root cause or legal responsibility.",
        "Identity matches rely on PPE, object labels, time, and movement—not facial recognition.",
      ],
      graph_metrics: {
        people: 5,
        objects_and_equipment: 4,
        zones: 5,
        observed_events: 8,
        evidence_clips: 6,
        graph_relationships: 42,
        jha_controls: 5,
        deviations: 4,
      },
      sponsor_trace: [
        { stage: "secure_uploads", sponsor: "AWS S3", status: "complete" },
        { stage: "parse_jha", sponsor: "OpenAI Terra", status: "complete" },
        { stage: "index_footage", sponsor: "TwelveLabs", status: "complete" },
        { stage: "connect_cameras", sponsor: "TwelveLabs Jockey", status: "complete" },
        { stage: "normalize_events", sponsor: "OpenAI Luna", status: "complete" },
        { stage: "write_context_graph", sponsor: "Neo4j AuraDB", status: "complete" },
        { stage: "graph_diff", sponsor: "Neo4j + Terra", status: "complete" },
        { stage: "verify_evidence", sponsor: "AWS Strands", status: "complete" },
        { stage: "draft_report", sponsor: "OpenAI Terra", status: "awaiting human approval" },
      ],
      generated_at: "2026-07-30T17:16:10Z",
    },
  };

  return { record, mediaUrls };
}
